import '../styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <html lang="pt-BR" className="dark"> // to set darkmode
    <html lang="pt-BR">
      <body
        className={`
        ${inter.className}
        max-w-screen-2xl
        mx-auto
        shadow-lg
        bg-gray-100`}
      >
        {children}
      </body>
    </html>
  );
}
